KTB-14 Взял chatid, вычислил текст и отправил sendMessage +refactor
Slavikus1/KotlinTelegramBot pull request #16
Opened 2024-09-28 09:40 UTC by Slavikus1

2024-09-30 05:59 UTC, danelyan requested changes

2024-09-30 05:59 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val urlGetUpdates = "https://api.telegram.org/bot$botToken/getUpdates?offset=$updateId"
`https://api.telegram.org/bot` - можно вынести в константу

2024-09-30 05:59 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +    fun getUpdates(botToken: String, updateId: Int?): String {
botToken - можно передать один раз в конструктор TelegramBotService и не прокидывать в каждый метод. 
Старайся обращать внимания на параметры, которые по факту никогда не меняются. В данном случае для TelegramBotService никогда не поменяется botToken

2024-09-30 05:59 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val client = HttpClient.newBuilder().build()
client можно создать один раз при создании TelegramBotService и переиспользовать в каждои методе

2024-10-01 11:47 UTC, kaznikit requested changes

2024-10-01 11:47 UTC, kaznikit commented on src/main/kotlin/TelegramBotService.kt
> +    private val httpClient: HttpClient = HttpClient.newBuilder().build(),
`httpClient` не стоит передавать в аргументы, лучше сделать его переменной класса и он будет создаваться при создании `TelegramBotService`

2024-10-02 07:49 UTC, kaznikit approved these changes

2024-10-05 13:20 UTC, merged